// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrincessChoice.Context;

#nullable disable

namespace PrincessChoice.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20221217171950_CreateAttempts")]
    partial class CreateAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PrincessChoice.DbModel.ContenderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttemptEntityId");

                    b.ToTable("Contender");
                });

            modelBuilder.Entity("PrincessChoice.DbModel.PrinceAttemptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AttemptName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrinceAttempt");
                });

            modelBuilder.Entity("PrincessChoice.DbModel.ContenderEntity", b =>
                {
                    b.HasOne("PrincessChoice.DbModel.PrinceAttemptEntity", "AttemptEntity")
                        .WithMany("Contenders")
                        .HasForeignKey("AttemptEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttemptEntity");
                });

            modelBuilder.Entity("PrincessChoice.DbModel.PrinceAttemptEntity", b =>
                {
                    b.Navigation("Contenders");
                });
#pragma warning restore 612, 618
        }
    }
}
