// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrincessChoice;
using PrincessChoice.Context;

#nullable disable

namespace PrincessChoice.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PrincessChoice.DbModel.ContenderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PrinceAttemptEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrinceAttemptEntityId");

                    b.ToTable("Contender");
                });

            modelBuilder.Entity("PrincessChoice.DbModel.PrinceAttemptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AttemptName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrinceAttempt");
                });

            modelBuilder.Entity("PrincessChoice.DbModel.ContenderEntity", b =>
                {
                    b.HasOne("PrincessChoice.DbModel.PrinceAttemptEntity", null)
                        .WithMany("Contenders")
                        .HasForeignKey("PrinceAttemptEntityId");
                });

            modelBuilder.Entity("PrincessChoice.DbModel.PrinceAttemptEntity", b =>
                {
                    b.Navigation("Contenders");
                });
#pragma warning restore 612, 618
        }
    }
}
